#!/bin/ksh

if [ -z "${REALSYNC_BASE}" ]
then
  cd ..
  REALSYNC_BASE=`pwd`
fi

Usage()
{
  echo "    ************************************************************************************"
  echo "    USAGE: del_service  SERVICE_NAME "
  echo "           SERVICE_NAME : please refer to ${REALSYNC_BASE}/config.srv"
  echo "                                          "
  echo "       SERVICE_NAME LIST:"
  for i in `cat ${REALSYNC_BASE}/config.srv | grep -v "#" | awk '{print $1}'`
  do
  echo "                         $i"
  done 
  echo "    ************************************************************************************"
  exit
}

if [ $# -lt 1 ]
then
  Usage
fi

DB_NAME=""
if [ ! -z "$SERVICE_NAME" ]
then
    DB_NAME=$SERVICE_NAME
else
    DB_NAME=$1
fi

SERVICENAME=`grep -w "$DB_NAME" ${REALSYNC_BASE}/config.srv`
if [ -z "$SERVICENAME" ]        
then
  echo "Warning: SERVICE_NAME $DB_NAME not found in ${REALSYNC_BASE}/config.srv."
  echo "SERVICE_NAME LIST:"
  for i in `cat ${REALSYNC_BASE}/config.srv | grep -v "#" | awk '{print $1}'`
  do
  echo "                  $i"
  done
  exit
fi

if [ ! -z "$SERVICE_NAME" ]
then
    rm -rf ${REALSYNC_BASE}/bin/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/config/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/log/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/xldr/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/vcfs/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/vcfsa/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/dbps/${DB_NAME}
    echo "$DB_NAME service is delete"
else
  read OPTION?"Do you really want to delete $DB_NAME service ? (Y/N):" 
  while true
  do
    if [ "$OPTION" != "Y" -a "$OPTION" != "y" -a "$OPTION" != "N" -a "$OPTION" != "n" ] 
    then
        read OPTION?"Do you really want to delete $DB_NAME service ? (Y/N):" 
    else
        break
    fi
  done
  if [ $OPTION = "Y" -o $OPTION = "y" ]
  then
    cd ${REALSYNC_BASE}/scripts
    ./stop_vagentd ${DB_NAME}
    rm -rf ${REALSYNC_BASE}/bin/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/config/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/log/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/xldr/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/vcfs/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/vcfsa/${DB_NAME}
    rm -rf ${REALSYNC_BASE}/dbps/${DB_NAME}
    sed /"${DB_NAME} "/d ${REALSYNC_BASE}/config.srv > ${REALSYNC_BASE}/config.srv.tmp
    mv ${REALSYNC_BASE}/config.srv.tmp ${REALSYNC_BASE}/config.srv
    cat ${REALSYNC_BASE}/config.srv
    echo "$DB_NAME service is delete"
  fi
  if [ $OPTION = "N" -o $OPTION = "n" ]
  then
    echo "no service delete"
  fi
fi

