#!/bin/ksh

if [ -z "${REALSYNC_BASE}" ]
then
  cd ..
  REALSYNC_BASE=`pwd`
fi

Usage()
{
  echo "    ************************************************************************************"
  echo "    USAGE: stop_r SERVICE_NAME [TYPE]"
  echo "           SERVICE_NAME : please refer to ${REALSYNC_BASE}/config.srv"
  echo "                                          "
  echo "       SERVICE_NAME LIST:"
  for i in `cat ${REALSYNC_BASE}/config.srv | grep -v "#" | awk '{print $1}'`
  do
  echo "                         $i"
  done 
  echo "                         all (stop_r all)"
  echo "    ************************************************************************************"
  exit
}

if [ $# -lt 1 -a -z "$SERVICE_NAME" ]
then
  Usage
fi

DB_NAME=""
if [ ! -z "$SERVICE_NAME" ]
then
    DB_NAME=$SERVICE_NAME
else
    DB_NAME=$1
fi

SERVICENAME=`grep -w "$DB_NAME" ${REALSYNC_BASE}/config.srv`
if [ -z "$SERVICENAME" -a "$DB_NAME" != "all" ]
then
  echo "Warning: SERVICE_NAME $DB_NAME not found in ${REALSYNC_BASE}/config.srv."
  echo "SERVICE_NAME LIST:"
  for i in `cat ${REALSYNC_BASE}/config.srv | grep -v "#" | awk '{print $1}'`
  do
  echo "                  $i"
  done
  echo "                  all (stop_r all)"
  exit
fi

stop_r()
{
 SYSTEM_ROLE=`grep -w "$DB_NAME" ${REALSYNC_BASE}/config.srv | awk '{print $4}'`
 if [ "${SYSTEM_ROLE}" = "TGT" ]
 then
   pid=`ps -ef | grep "loader -r" | grep -w "$DB_NAME" | grep -v grep | awk '{print $2}'`
   if [ ! -z "$pid" ]
   then
       echo "r" > ${REALSYNC_BASE}/xldr/${DB_NAME}/run_state.ctl
       sleep 2
       pid=`ps -ef | grep "loader -r" | grep -w "$DB_NAME" | grep -v grep | awk '{print $2}'` 
       while [ ! -z "$pid" ]
       do
           echo "$1 loader -r do not Stopped,retry stop it ..."
           sleep 3
           pid=`ps -ef | grep "loader -r" | grep -w "$DB_NAME" | grep -v grep | awk '{print $2}'`
       done
       echo "$1 loader -r Stopped"
       mv ${REALSYNC_BASE}/xldr/${DB_NAME}/run_state.ctl ${REALSYNC_BASE}/xldr/${DB_NAME}/run_state.ctl.bak
    fi
 fi
}

if [ "${DB_NAME}" != "all" ]
then
  stop_r ${DB_NAME}
else
  for i in `cat ${REALSYNC_BASE}/config.srv |grep -v "#" |grep -v grep | awk '{print $1}'`
  do
    stop_r $i
    sleep 1
  done
fi
