#!/bin/ksh

if [ -z "${REALSYNC_BASE}" ]
then
  cd ..
  REALSYNC_BASE=`pwd`
fi

Usage()
{
  echo "    ************************************************************************************"
  echo "    USAGE: start_msld SERVICE_NAME "
  echo "           SERVICE_NAME : please refer to ${REALSYNC_BASE}/config.srv or all"
  echo "                                          "
  echo "       SERVICE_NAME LIST:"
  for i in `cat ${REALSYNC_BASE}/config.srv | grep -v "#" | awk '{print $1}'`
  do
  echo "                         $i"
  done 
  echo "                         all (start all)"
  echo "    ************************************************************************************"
  exit
}

if [ $# -lt 1 ]
then
  Usage
fi

DB_NAME="$1"

SERVICENAME=`grep -w "$DB_NAME" ${REALSYNC_BASE}/config.srv`
if [ -z "$SERVICENAME" -a "$DB_NAME" != "all" ]        
then
  echo "Warning: SERVICE_NAME $DB_NAME not found in ${REALSYNC_BASE}/config.srv."
  echo "SERVICE_NAME LIST:"
  for i in `cat ${REALSYNC_BASE}/config.srv | grep -v "#" | awk '{print $1}'`
  do
  echo "                  $i"
  done
  echo "                  all (start all)"
  exit
fi

start_msld()
{
    export PA="-parfile ${REALSYNC_BASE}/config/$1/msl.ini"
    DATE=`date +%Y%m%d%H%M%S`
    pid=`ps -ef |grep -w $1 |grep -w msld|grep -v grep|awk '{print $2}'`
    if [ -z "$pid" ]
    then
        mv ${REALSYNC_BASE}/log/$1/log.msld ${REALSYNC_BASE}/log/$1/oldlog/log.msld${DATE}
        ${REALSYNC_BASE}/bin/$1/msld $PA > ${REALSYNC_BASE}/log/$1/log.msld 2>&1 &
        sleep 1
        pid=`ps -ef |grep -w $1 |grep -w msld|grep -v grep|awk '{print $2}'`
        #sleep 1
        if [ ! -z "$pid" ]
        then
            echo "Parallel msld Started!($1)"
            ps -ef |grep -w $1 |grep -w msld|grep -v grep
        else
            echo "Parallel msld Start Unsuccess,Please check it.($1)"
        fi
    else
        echo "Parallel msld is Running!($1)"
    fi 
}

if [ "$DB_NAME" != "all" ]
then
    start_msld $1
else
    for k in `cat ${REALSYNC_BASE}/config.srv | grep -v "#" | awk '{print $1}'`
    do
      start_msld $k
    done
fi


